CREATE TABLE /*TABLE_PREFIX*/t_voting_item (
    fk_i_item_id INT UNSIGNED NOT NULL,
    fk_i_user_id INT UNSIGNED,
    i_vote INT UNSIGNED NOT NULL,
    s_hash VARCHAR(255) NULL,
        FOREIGN KEY (fk_i_item_id) REFERENCES /*TABLE_PREFIX*/t_item (pk_i_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';

CREATE TABLE /*TABLE_PREFIX*/t_voting_user (
    i_user_voted INT(10) UNSIGNED NOT NULL,
    i_user_voter INT(10) UNSIGNED NOT NULL,
    i_vote INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';