/* MAKES */
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (1,'Acura');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (2,'Audi');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (3, 'Alfa Romeo');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (3,'Alfa Romeo');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (4,'Aston Martin');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (5,'BMW');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (6,'Buick');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (7,'Cadillac');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (8,'Chevrolet');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (9,'Chrysler');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (10,'Datsun');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (11,'Dodge');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (12,'FAW');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (14,'Ferrari');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (15,'Fiat');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (16,'Ford');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (17,'GEO');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (18,'GMC');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (19,'Honda');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (20,'Hummer');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (21,'Hyundai');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (22,'Infiniti');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (23,'Izusu');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (24,'Jaguar');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (25,'Jeep');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (26,'Lamborghini');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (27,'Land Rover');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (28,'Lincoln');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (29,'Maserati');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (30,'Mazda');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (31,'Mercedes Benz');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (32,'Mercury');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (33,'Villager');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (34,'MG');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (35,'Mini');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (36,'Mitsubishi');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (37,'Nissan');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (38,'Oldsmobile');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (39,'Peugeot');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (40,'Plymouth');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (41,'Pontiac');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (42,'Porsche');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (43,'Rambler');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (44,'Renault');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (45,'RollsRoyce');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (46,'Rove');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (47,'Saab');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (48,'Seat');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (49,'Smart');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (50,'Suzuki');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (51,'Toyota');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (52,'Volkswagen');
INSERT INTO /*TABLE_PREFIX*/t_item_car_make_attr (pk_i_id, s_name) VALUES (53,'Volvo');

/* MODELS */
/* MAKE: Acura */
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (1, 'TL');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (1, 'MDX');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (1, 'RDX');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (1, 'RL');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (1, 'Integra');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (1, 'TSX');
/* MAKE: Audi */
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'A1');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'A3');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'A4');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'A5');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'A6');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'A8');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'S3');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'S4');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'S5');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'S6');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'S8');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'RS4');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'RS6');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'R8');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'Allroad');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'Q5');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (2, 'Q7');
/* MAKE: Alfa Romeo */
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (3, '156');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (3, '147');
/* MAKE: Aston Martin */
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (4, 'DB9');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (4, 'DBS');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (4, 'Vantage');
/* MAKE: BMW */
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, '1600');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'M Z4');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'M1');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'M3');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'M5');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'M6');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'Serie 1');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'Serie 3');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'Serie 5');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'Serie 6');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'Serie 7');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'Serie 8');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'X1');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'X3');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'X5');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'X6');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'X6 M');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'Z3');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (5, 'Z4');
/* MAKE: Buick */
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (6, 'Enclave');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (6, 'LaCrosse');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (6, 'LeSabre');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (6, 'Otro');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (6, 'Regal');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (6, 'Riviera');
/* MAKE: Cadillac */
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (7, 'BLS');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (7, 'Catera');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (7, 'Concours');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (7, 'CTS');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (7, 'Deville');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (7, 'DHS');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (7, 'Escalade');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (7, 'Seville');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (7, 'SRX');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (7, 'STS');
/* MAKE: Chevrolet */
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, '1500');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, '210');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, '400');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, '454');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Apache');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Astra');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Astro');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Avalanche');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Aveo');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Bell Air');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Blazer');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Bravada');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'C 350');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'C 3500');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'C-15');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'C-20');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'C36');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Camaro');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Captiva');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Cavalier');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Chevy');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Chevy Monza');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Cheyenne');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Citation-x11');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Colorado');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Corsa');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Corsica');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Corvette');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Cruze');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Custom');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Cutlass');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Deluxe');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'El Camino');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Epica');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Equinox');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Eurocar');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'G-30');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'HHR');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Impala');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Kodiac');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'LUV');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Malibu');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Matiz');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Meriva');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Montecarlo');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Monza');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Monza C2');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'OldsMobile');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Optra');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Pop');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'S 10');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Safari');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Sierra');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Silhouete');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Silverado');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Sonora');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Spark');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Suburban');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Tahoe');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Tornado');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Tracker');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Trailbalzer');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Transport');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Uplander');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Vanette');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Vectra');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Venture');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Yukon');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (8, 'Zafira');
/* Make: Chrysler */
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, '300 C');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, '300 M');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Aspen');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Atos');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Caravan');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Cirrus');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Concorde');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Crossfire');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'D-350');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Grand Caravan');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Grand Voyager');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Intrepid');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Le Baron');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'LHS');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Neon');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'New Yorker');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Pacifica');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'PT Cruiser');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'RAM');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Sebring');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Shadow');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Stratus');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Town Country');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Valiant');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (9, 'Voyager');
/* MAKE: Datsun */
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (10, 'Sedan');
/* MAKE: Dodge */
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, '1000');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Atos');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Attitude');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Avenger');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Caravan');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Challenger');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Charger');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Coronet');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'D 600');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'D-150');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'D-250');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'D-350');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Dakota');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Dart');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Durango');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Grand Caravan');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'H-100');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Intrepid');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Journey');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Neon');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Nitro');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'RAM');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Royal Mónaco');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Stealth');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Stratus');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Valiant');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Vanette');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Verna');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (11, 'Viper');
/* MAKE: FAW */
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (12, 'F1');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (12, 'F4');
INSERT INTO /*TABLE_PREFIX*/t_item_car_model_attr (fk_i_make_id, s_name) VALUES (12, 'F5');

