<?php

    $mobiles = array(  'mobileexplorer'       => 'Mobile Explorer',
                       'palmsource'           => 'Palm',
                       'palmscape'            => 'Palmscape',
                       // Phones and Manufacturers
                       'motorola'             => "Motorola",
                       'nokia'                => "Nokia",
                       'palm'                 => "Palm",
                       'iphone'               => "Apple iPhone",
                       'ipad'                 => "iPad",
                       'ipod'                 => "Apple iPod Touch",
                       'sony'                 => "Sony Ericsson",
                       'ericsson'             => "Sony Ericsson",
                       'blackberry'           => "BlackBerry",
                       'cocoon'               => "O2 Cocoon",
                       'blazer'               => "Treo",
                       'lg'                   => "LG",
                       'amoi'                 => "Amoi",
                       'xda'                  => "XDA",
                       'mda'                  => "MDA",
                       'vario'                => "Vario",
                       'htc'                  => "HTC",
                       'samsung'              => "Samsung",
                       'sharp'                => "Sharp",
                       'sie-'                 => "Siemens",
                       'alcatel'              => "Alcatel",
                       'benq'                 => "BenQ",
                       'ipaq'                 => "HP iPaq",
                       'mot-'                 => "Motorola",
                       'playstation portable' => "PlayStation Portable",
                       'hiptop'               => "Danger Hiptop",
                       'nec-'                 => "NEC",
                       'panasonic'            => "Panasonic",
                       'philips'              => "Philips",
                       'sagem'                => "Sagem",
                       'sanyo'                => "Sanyo",
                       'spv'                  => "SPV",
                       'zte'                  => "ZTE",
                       'sendo'                => "Sendo",
                       // Operating Systems
                       'symbian'              => "Symbian",
                       'SymbianOS'            => "SymbianOS",
                       'elaine'               => "Palm",
                       'palm'                 => "Palm",
                       'series60'             => "Symbian S60",
                       'windows ce'           => "Windows CE",
                       // Browsers
                       'obigo'                => "Obigo",
                       'netfront'             => "Netfront Browser",
                       'openwave'             => "Openwave Browser",
                       'mobilexplorer'        => "Mobile Explorer",
                       'operamini'            => "Opera Mini",
                       'opera mini'           => "Opera Mini",
                       'operamobi'            => "Opera Mobi",        
                       'opera mobi'           => "Opera Mobi",
                       'maemo'                => "Maemo Browser",
                       // Other
                       'digital paths'        => "Digital Paths",
                       'avantgo'              => "AvantGo",
                       'xiino'                => "Xiino",
                       'novarra'              => "Novarra Transcoder",
                       'vodafone'             => "Vodafone",
                       'docomo'               => "NTT DoCoMo",
                       'o2'                   => "O2",
                       // Fallback
                       'mobile'               => "Generic Mobile",
                       'wireless'             => "Generic Mobile",
                       'j2me'                 => "Generic Mobile",
                       'midp'                 => "Generic Mobile",
                       'cldc'                 => "Generic Mobile",
                       'up.link'              => "Generic Mobile",
                       'up.browser'           => "Generic Mobile",
                       'smartphone'           => "Generic Mobile",
                       'cellphone'            => "Generic Mobile" );

?>